### ISSUE TITLE
﻿﻿﻿Ultrasonic Sensor Timed out, Restarting.

### ISSUE THREAD

**Issue by Waterbrain** [node-red/node-red-nodes#436] opened 2018-04-19 12:16 UTC
Hello:
I have installed node-red-node-pisrf and I can not get it to work, I tested with pins 22 and 24 or 16 and 18 and its operation is quite erratic.
Sometimes it works, I've seen it with my own eyes, but I usually get that error.
Someone could help me.
Thank you.

**Comment by dceejay** [comment] 2018-04-19 18:44
As per project contribution guidelines we prefer general questions and how-to via the mailing list or slack channels so the wider community can help rather than rely on the core developers to have time to try to help out.
duplicate of #420.

**Closed by dceejay** 2018-04-19 18:44 UTC
Labels: duplicate
