### ISSUE TITLE
Serialport does not successfully compile, +15 compile errors

### ISSUE THREAD

**Issue by jwcrawley** [node-red/node-red-nodes#153] opened 2015-12-09 16:41 UTC
Multiple compile issues. 
Running nodejs 5.2.0

http://pastebin.com/pHek7VDy

**Comment by dceejay** [comment] 2015-12-09 16:58
This should be fixed by #139. We have a fix in test at the moment - works on Node 4.2.3 (LTS).

**Comment by jwcrawley** [comment] 2015-12-09 18:10
That is awesome to hear. I'd also be willing to test any experimental packages on my dev system, if you'd like.

Again, thank you.

**Comment by dceejay** [comment] 2015-12-09 19:50
Closing as a duplicate of #139

**Closed** 2015-12-09 19:53 UTC
Labels: duplicate
