### ISSUE TITLE
Node-red Debug node accepts script in its name field and executes the script on enable/disable of debug node 

### ISSUE THREAD

**Issue by Sebanti13** [node-red/node-red-nodes#755] opened 2021-02-09 07:17 UTC
![debug node Name field accepting script](https://user-images.githubusercontent.com/20661356/107327905-e8b8c900-6ad3-11eb-8cdb-4983684d746e.jpg)
![Node-red page unresponsive](https://user-images.githubusercontent.com/20661356/107327915-e9e9f600-6ad3-11eb-96d1-09dfeeff3227.jpg)

### What are the steps to reproduce? 
1. Drag and drop the debug node in the flow.
2. Open the node configuration of debug node.
2. In the Name field, enter the script tag <script>while(1);</script> and click on Done.
3. Deploy the Flow.
4. Enable/Disable the debug node.

### What happens?
The node-red page becomes unresponsive, since the while(1) statement in the script tag gets executed.

### What do you expect to happen?
Script tag should not be accepted or executed by the Debug node.

### Please tell us about your environment:

- [x] Node-RED version: latest - version 1.2.7
- [x] node.js version: 12.18.3
- [x] npm version: 6.14.6
- [x] Platform/OS: Windows 10
- [x] Browser: Chrome Version 88.0.4324.104

**Comment by knolleary** [comment] 2021-02-09 09:27
I cannot reproduce this issue.

I have set the name of a Debug node to `<script>console.warn("BOOM");</script>` so that rather than hang the editor, we'll get a log message and be able to identify where in the DOM it has been added. But I don't get any messages.

Can you try with that script and see if you can identify where in the page the script has been added - that will help us narrow down where it is being added.

**Comment by Sebanti13** [comment] 2021-02-09 12:50
Yes, here I've sent a snippet of the BOOM warning logged in browser console, **when I click on the enable/disable button** of the debug node:
![image](https://user-images.githubusercontent.com/20661356/107364580-a4442200-6b01-11eb-9789-8daba39df2f8.png)

After that, it gets added into the meta section of the debug message:
![image](https://user-images.githubusercontent.com/20661356/107365394-becacb00-6b02-11eb-941b-917ec1adc07f.png)
 - This happens for all the subsequent debug messages.
 
Another place I've observed it appears in the DOM is in the below section:

![image](https://user-images.githubusercontent.com/20661356/107365670-2254f880-6b03-11eb-8011-637dc1e6b36d.png)
- Not sure about the impact of this section in the node-red page.

**Comment by knolleary** [comment] 2021-02-09 13:10
Very strange - still not able to reproduce this.

Both of the `<script>` screenshots you show is 'expected' - you can see there's no highlighting as it is being properly treated as text, not HTML. So they are not where the script is being evaluated.



If you click here: 
![image](https://user-images.githubusercontent.com/51083/107368250-3a635280-6ad8-11eb-9e1e-1cfe8b944905.png)

where does it take you?

**Comment by knolleary** [comment] 2021-02-09 15:05
I've managed to recreate. I was using the disable/enable option in the node's edit dialog - not the button on the node itself.

I've pushed the fix to the main node-red repo where the Debug node lives - https://github.com/node-red/node-red/commit/dd780945e1e03cdd15ab50275083ca6fe0674916

Will be in the next release.

**Closed by knolleary** 2021-02-09 15:05 UTC
