### ISSUE TITLE
node-red-node-sqlite new INSERT with '$' puts the node into error state

### ISSUE THREAD

**Issue by nerevaer** [node-red/node-red-nodes#870] opened 2022-01-05 08:39 UTC
### Which node are you reporting an issue on?
node-red-node-sqlite

### What are the steps to reproduce?
Insert data using: 
`INSERT INTO users_connection_data (ip, connected, date) VALUES ($1, $2, $3);`
or
`INSERT INTO users_connection_data (ip, connected, date) VALUES ($ip, $connected, $date);`
with the payload for binding:
`["192.168.3.161",1,1641368629093]`

Table was created using:
`CREATE TABLE users_connection_data(id INTEGER PRIMARY KEY AUTOINCREMENT, ip TEXT, connected INTEGER, date INTEGER);`

### What happens?
After the insert  the node goes into the error state and does not work until Restart Flows.

### What do you expect to happen?
To insert the data and afterwords be able to use the node.

### Please tell us about your environment:
Node-RED version: v2.1.4
Node.js  version: v14.18.2
Linux 4.19.95-rt38-v7 arm LE (debian 10)
node-red-node-sqlite v1.01

**Comment by hardillb** [comment] 2022-01-05 08:47
Please add some more detail here. 

- How are you passing the INSERT Query, `msg.topic`, prepared statement, fixed statement?
- Shouldn't the parameters be in `msg.params` as an object not an array

Can you supply a sample flow that shows the problem?

**Comment by hardillb** [comment] 2022-01-05 08:52
Also if raising issues based on Forum discussions it helps to link to the discussion in the issue.

https://discourse.nodered.org/t/sqlite3-data-insert-problem/56075/29

**Comment by nerevaer** [comment] 2022-01-05 08:53
I'm passing it as a msg.topic.

screenshot of the flow:
![image](https://user-images.githubusercontent.com/87225499/148188842-95c9b725-24d4-4c3d-a873-513ff4525a2f.png)


flow:
```[
    {
        "id": "a60e91b5915609fc",
        "type": "inject",
        "z": "8bef5da1.57771",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 580,
        "y": 1240,
        "wires": [
            [
                "de7e73e05e08ef47"
            ]
        ]
    },
    {
        "id": "4689b4c9b76e0236",
        "type": "inject",
        "z": "8bef5da1.57771",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 580,
        "y": 1280,
        "wires": [
            [
                "1059687386b3063c"
            ]
        ]
    },
    {
        "id": "de7e73e05e08ef47",
        "type": "function",
        "z": "8bef5da1.57771",
        "name": "select",
        "func": "var curr_n, dt, ts, socketip, socketid, topic, payload, prev_n;\nmsg = {};\nts = 1641368629093;\nsocketip = \"192.168.3.161\";\nsocketid = \"pAbid2ZQ1CMka120AAAn\";\n\n\n    msg1 = {\n        topic: \"SELECT * FROM users_connection_data ORDER BY id DESC;\",\n        //socketip: socketip,\n        //socketid: socketid,\n        //pull: true\n    };\n    return msg1;\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 710,
        "y": 1240,
        "wires": [
            [
                "d906b4f6f075dc30",
                "fdac955167602bb7"
            ]
        ]
    },
    {
        "id": "1059687386b3063c",
        "type": "function",
        "z": "8bef5da1.57771",
        "name": "first input",
        "func": "var curr_n, dt, ts, socketip, socketid, topic, payload, prev_n;\nmsg = {};\nts = 1641368629093;\nsocketip = \"192.168.3.161\";\nsocketid = \"pAbid2ZQ1CMka120AAAn\";\ncurr_n = 1;\n        msg1 = {\n            topic: \"INSERT INTO users_connection_data (ip, connected, date) VALUES ($ip, $connected, $date);\",\n            payload: [socketip, curr_n, ts],\n            //socketip: socketip,\n            //socketid: socketid\n        };\n        return msg1;\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 720,
        "y": 1280,
        "wires": [
            [
                "4ec4545fe2370525",
                "fdac955167602bb7"
            ]
        ]
    },
    {
        "id": "4ec4545fe2370525",
        "type": "debug",
        "z": "8bef5da1.57771",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 930,
        "y": 1320,
        "wires": []
    },
    {
        "id": "d906b4f6f075dc30",
        "type": "debug",
        "z": "8bef5da1.57771",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 930,
        "y": 1280,
        "wires": []
    },
    {
        "id": "fdac955167602bb7",
        "type": "function",
        "z": "8bef5da1.57771",
        "name": "fw",
        "func": "\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 930,
        "y": 1240,
        "wires": [
            [
                "3f4e144d27d9130f"
            ]
        ]
    },
    {
        "id": "1e34397f9e4ee12d",
        "type": "inject",
        "z": "8bef5da1.57771",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 580,
        "y": 1320,
        "wires": [
            [
                "ff4e50838e3bb65b"
            ]
        ]
    },
    {
        "id": "ff4e50838e3bb65b",
        "type": "function",
        "z": "8bef5da1.57771",
        "name": "update",
        "func": "var curr_n, dt, ts, socketip, socketid, topic, payload, prev_n;\nmsg = {};\nts = 1641368699093;\nsocketip = \"192.168.3.161\";\nsocketid = \"pAbid2ZQ1CMka120AAAn\";\ncurr_n = 1;\n        msg1 = {\n                topic: \"UPDATE users_connection_data SET connected = ?, date = ? WHERE ip = ?;\",\n                payload: [curr_n, ts, socketip],\n                socketip: socketip,\n                socketid: socketid\n        };\n        return msg1;\n\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 710,
        "y": 1320,
        "wires": [
            [
                "fdac955167602bb7",
                "df0caf76bbd58e99"
            ]
        ]
    },
    {
        "id": "398ab8e31c8e4eb3",
        "type": "debug",
        "z": "8bef5da1.57771",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1130,
        "y": 1280,
        "wires": []
    },
    {
        "id": "3f4e144d27d9130f",
        "type": "sqlite",
        "z": "8bef5da1.57771",
        "mydb": "73ac2ee8378b3e02",
        "sqlquery": "msg.topic",
        "sql": "",
        "name": "ODIN_petr_log",
        "x": 1100,
        "y": 1240,
        "wires": [
            [
                "398ab8e31c8e4eb3"
            ]
        ]
    },
    {
        "id": "aa7c3bf34899f41a",
        "type": "inject",
        "z": "8bef5da1.57771",
        "name": "DROP TBL",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "DROP TABLE users_connection_data;",
        "payloadType": "date",
        "x": 320,
        "y": 1300,
        "wires": [
            [
                "c78a03e85194f71e"
            ]
        ]
    },
    {
        "id": "a9d3c4ba6d84c379",
        "type": "inject",
        "z": "8bef5da1.57771",
        "name": "SELECT",
        "props": [
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "SELECT * FROM users_connection_data ORDER BY id DESC;",
        "x": 320,
        "y": 1260,
        "wires": [
            [
                "c78a03e85194f71e"
            ]
        ]
    },
    {
        "id": "6a8ea8c43bc2490b",
        "type": "inject",
        "z": "8bef5da1.57771",
        "name": "CREATE users_connection_data",
        "props": [
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "CREATE TABLE users_connection_data(id INTEGER PRIMARY KEY AUTOINCREMENT, ip TEXT, connected INTEGER, date INTEGER);",
        "x": 250,
        "y": 1220,
        "wires": [
            [
                "c78a03e85194f71e"
            ]
        ]
    },
    {
        "id": "c78a03e85194f71e",
        "type": "sqlite",
        "z": "8bef5da1.57771",
        "mydb": "73ac2ee8378b3e02",
        "sqlquery": "msg.topic",
        "sql": "",
        "name": "ODIN_petr_log",
        "x": 340,
        "y": 1180,
        "wires": [
            [
                "70084233496c36f6"
            ]
        ]
    },
    {
        "id": "70084233496c36f6",
        "type": "debug",
        "z": "8bef5da1.57771",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 350,
        "y": 1140,
        "wires": []
    },
    {
        "id": "df0caf76bbd58e99",
        "type": "debug",
        "z": "8bef5da1.57771",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 930,
        "y": 1360,
        "wires": []
    },
    {
        "id": "73ac2ee8378b3e02",
        "type": "sqlitedb",
        "db": "ODIN_petr_log.db",
        "mode": "RWC"
    }
]
```

**Comment by hardillb** [comment] 2022-01-05 09:23
Can you add a description of the order that the inject nodes should be fired in that example, because I'm not seeing the error.

**Comment by nerevaer** [comment] 2022-01-05 09:52
Yes. 
1. CREATE table
2. SELECT (to check if it exists and if empty)
3. INSERT (with bind)
4. SELECT (to check if data was inserted) --> error
![image](https://user-images.githubusercontent.com/87225499/148197270-81bf74f1-f8c8-4574-b893-f10aa105083b.png)

**Comment by nerevaer** [comment] 2022-01-05 09:58
Maybe is a problem in my instalation? I get this message:
![image](https://user-images.githubusercontent.com/87225499/148198322-104b3d15-1c8b-42f0-8652-feb0eeba53aa.png)

**Comment by hardillb** [comment] 2022-01-05 10:02
any npm commands should be run in the Node-RED userDir (usually `~/.node-red`) not your home directory but this is not related to what you have installed.

I can now recreate the problem.

**Comment by hardillb** [comment] 2022-01-05 10:06
I think I know what the problem is, it looks like the `bind` variable is not being reset for the later query.

https://github.com/node-red/node-red-nodes/blob/e6930274e25ad85c43da3e26096e6732ab08dc46/storage/sqlite/sqlite.js#L56-L59

This if block should have an else that resets `bind` to `[]`

**Comment by hardillb** [comment] 2022-01-05 10:35
PR with a fix https://github.com/node-red/node-red-nodes/pull/872

**Comment by hardillb** [comment] 2022-01-05 11:05
Can you test this fix please before we merge.

- stop Node-RED
- In the userDir run the following: `npm install "https://github.com/hardillb/node-red-nodes.git#sqlite3-fix"`
- restart Node-RED

The npm install should pull directly from my branch in github

**Comment by knolleary** [comment] 2022-01-05 11:18
@hardillb not sure that npm path is right... that'll install the root of the mono repo, not the sqlite node?

**Comment by hardillb** [comment] 2022-01-05 11:21
Doh, good point. Will work out the foo for a path in a branch

**Comment by hardillb** [comment] 2022-01-05 11:46
OK, no way to npm install from a subdir so swap the install command for this:

`npm install node-red-node-sqlite@1.02`

You will still need to restart Node-RED. Assuming all good we will update the catalogue on flows

**Comment by colinl** [comment] 2022-01-05 11:57
How do I undo the original npm install?  If necessary.

**Comment by hardillb** [comment] 2022-01-05 12:00
@colinl `npm uninstall node-red-nodes`

**Comment by nerevaer** [comment] 2022-01-05 13:42
@hardillb It works now with a minor correction: `npm install node-red-node-sqlite@1.0.2` (1.0.2, not 1.02)

**Comment by hardillb** [comment] 2022-01-05 13:47
Cool, I'll close this now

**Closed by hardillb** 2022-01-05 13:47 UTC
