### ISSUE TITLE
Ping stopped working on HA (Home Assistant)

### ISSUE THREAD

**Issue by PierreScerri** [node-red/node-red-nodes#662] opened 2020-07-08 07:21 UTC
### Which node are you reporting an issue on?
Ping
### What are the steps to reproduce?
Inject node to trigger ping node set to 'Triggered' and a specific IP address was giving a time value or False until a few days ago.

The log gives:

`8 Jul 09:21:33 - [info] [ping:a36f42a9.ccecc] ping - Host '192.168.1.162' process timeout - sending SIGINT
`
### What happens?
Outputs Trip Time when IP responds but does not report false when the IP does not respond.
### What do you expect to happen?
Outputs Trip Time or False as it was doing a few days ago
### Please tell us about your environment:

- [1.0.6 ] Node-RED version:
- [ 12.15.0] node.js version:
- [?] npm version:
- [Hassos ] Platform/OS:
- [Any] Browser:

**Comment by masterfish1** [comment] 2020-07-11 10:52
I'm having this issue to but thought it was due to the new NodeRed update to 1.10. Presumably not if OP has the same issue in 1.0.6.

**Comment by knolleary** [comment] 2020-07-11 11:09
@PierreScerri what version of the ping node have you got installed? You can check via the palette manager.

Did you update it or any other part of the system? The node isn't going to have stopped working all by itself.

Can you manually ping the up address from the command line?

It's far more likely something external to the node is causing the timeout.

**Comment by PierreScerri** [comment] 2020-07-11 11:40
ping version 0.2.1
Yes I can ping the address manaually.

I am testing with a timed ping node every 5s and a debug message.

When the address responds I get a message
When the address does not respond nothing comes out of the ping node.

I cannot explain it simpler than that.

**Comment by masterfish1** [comment] 2020-07-11 12:21
I'm the same, version 0.2.1 and can ping the address manually using CMD. I have it with a timed ping of 20s but it is also the same issue when triggered with an inject node. I'm using the NodeRed add-on inside Home Assistant.

I just tested it in an old install on Windows (Node-Red version 0.20.8) and it works as expected. I then updated Node-Red to 1.1.2 and it still works.

Finally, I downgraded Node-Red to 1.1.0 on Windows to match what I have in HA and it works as expected.

Seems the issue is with Home Assistant. No idea what it could be though.

**Comment by papperone** [comment] 2020-07-18 11:33
I've exactly the same problem with Nodered as HA addon; so is there any solution? is it confirmed it's a HA issue only?

**Comment by PierreScerri** [comment] 2020-07-18 12:11
My solution was to use another ping node from the library

**Comment by papperone** [comment] 2020-07-18 12:43
> 
> 
> My solution was to use another ping node from the library
> 
> https://flows.nodered.org/node/node-red-contrib-advanced-ping

I can confirm this other node works perfectly, I spoke as well on HA Discord and nothing can be broken on that side, and as others PING nodes works the issue is specific to this node that fails with latest updated under HA

**Comment by papperone** [comment] 2020-07-18 12:59
CONFIRMED: issue is related to latest 0.2.1 running under Alpine/Linux; reverting to 0.2.0 the node works as expected.

**Comment by PierreScerri** [comment] 2020-07-18 13:10
Out of curiosity how do you revert to an older version?

**Comment by papperone** [comment] 2020-07-18 14:30
> 
> 
> Out of curiosity how do you revert to an older version?

test was done by one of the HA developper and reported to me

**Comment by PierreScerri** [comment] 2020-07-18 14:31
Ok Thanks

**Comment by dceejay** [comment] 2020-07-18 21:18
Just to clarify. Does it work at all on HA 0.2.1 ?
The node has always sent a null object if no reply, maybe they are no longer handling nulls for some reason ?

**Comment by PierreScerri** [comment] 2020-07-18 21:40
It was only sending trip time if the IP address responded. Otherwise it did not Sen anything. I.e. If the device was unavailable the ping node would not tell you.

**Comment by dceejay** [comment] 2020-07-18 22:01
This is direct to a debug node ?

**Comment by PierreScerri** [comment] 2020-07-18 22:24
Yes and anything else you'd care to connect to it

**Comment by DConcord** [comment] 2020-09-06 17:54
Chiming in - same issue on 0.2.1: Ping works fine when the host is up, but no output when the host is down

**Comment by Sebazzz** [comment] 2020-09-13 13:35
I didn't have it in 1.6.1, but I do have it in 1.7.x. I'm also running it as a Home Assistant add-in.

**Comment by j9brown** [comment] 2020-11-18 21:14
Same problem.  I think I've tracked it down to a bug in how the Ping nodes handles timeouts of the spawned ping command.

As far as I can tell, the Home Assistant implementation of the "ping" command doesn't support variable timeouts (it ignores all command-line options).  It always times out after 10 seconds if the host is not found.  Meanwhile the Ping node's default timeout is 5 seconds and it allows one second of grace for "ping" to return before killing it.  The interaction of these two behaviors results in the Ping node's timeout logic being invoked unless the user overrides the timeout (say, by setting it to 10000 milliseconds).

The way the code is currently written, Ping timeouts do not produce any output.  For robustness, I think we should consider changing this so that Ping command timeouts and other errors emit appropriate messages to the node's output port.

[Relevant code](https://github.com/node-red/node-red-nodes/blob/master/io/ping/88-ping.js#L44)

**Comment by dceejay** [comment] 2020-11-19 15:05
not quite sure I understand your logic yet. Are you saying we should kill it at exactly the time it times out (not grace) or something else ? Either way it should then retry again and that seems to be the issue that it stops responding completely.

**Comment by j9brown** [comment] 2020-11-19 20:58
I’m saying that we should change the code so that the node produces an output for each attempted ping regardless of what happened.  So if the ping command can’t run or hangs and has to be killed, the node should send a message saying that’s what happened (may be ok to collapse into the “false” state or define some other output for such error conditions).

No need to retry (just wait for the timer or trigger input to kick in again).

**Comment by hardillb** [comment] 2020-11-19 21:01
We can't just add new output messages as that could break existing flows, but it could throw errors that could be caught by the `catch` node

**Comment by PierreScerri** [comment] 2020-11-19 22:25
May I remind you that this node was previously working as expected.  ie when the pinged host is non-responsive, the node will report this after a timeout.  This behaviour stopped in one of the later updates.

**Comment by dceejay** [comment] 2020-11-20 14:03
err - really... ? If I ping an unresolvable address I get back a payload boolean false. If I ping a resolvable but unreachable box it times out and I get back a payload boolean false... so it is working as previously. This is with version 0.2.1 of the ping node. I thought the issue was that it stops working after a random period and never recovers from that. If this is not that then yes it is something different but is working here. How are you checking the output of the ping ? Is HA maybe ignoring the false as it is not a number ?

**Comment by PierreScerri** [comment] 2020-11-20 16:13
Yes really.  Nothing was coming out of the ping node if there was no response.
That was the issue.
I have just tried it now with a device that is off and there is no response from the ping node.
Inject node every 20 seconds, the device that is on responds as expected, but the device that is off does not.

![Screenshot 2020-11-20 at 17 12 14](https://user-images.githubusercontent.com/34303331/99822552-a37b9f80-2b53-11eb-99c1-646cacf43809.png)

**Comment by dceejay** [comment] 2020-11-20 17:18
Which version of he ping node is this ?
As I said with a simple flow like yours I get
![image](https://user-images.githubusercontent.com/5375409/99829502-492f0e80-2b54-11eb-957b-42ad96e96351.png)

```
[{"id":"1f8b22eb.168d7d","type":"inject","z":"3e6448b5.f21398","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":160,"y":660,"wires":[["28498421.a39b2c"]]},{"id":"28498421.a39b2c","type":"ping","z":"3e6448b5.f21398","mode":"triggered","name":"","host":"192.168.1.11","timer":"30","inputs":1,"x":340,"y":660,"wires":[["d73f3bc2.23ce88"]]},{"id":"d73f3bc2.23ce88","type":"debug","z":"3e6448b5.f21398","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":500,"y":660,"wires":[]}]
```

**Comment by PierreScerri** [comment] 2020-11-20 17:27
That's what I used to get in ver0.2.0 I think.

I have node-red-node-ping ver 0.2.1 and it's not giving false.

Tried your flow in my setup and there is no output.

**Comment by dceejay** [comment] 2020-11-20 17:32
![image](https://user-images.githubusercontent.com/5375409/99831001-6369ec00-2b56-11eb-94fa-2efd094babff.png)

**Comment by PierreScerri** [comment] 2020-11-20 17:35
Other people have experienced this, so I'm not the only one.

I'm running node-red as an add-on to homeassistant.

**Comment by dceejay** [comment] 2020-11-20 17:36
I'm not... I'm not sure how/why they could/would break it though. Maybe ask them :-)

**Comment by hardillb** [comment] 2020-11-20 17:37
Just to be clear here, you are running the homeassistant whole OS image?

It sounds like they are not shipping the same `ping` binary as say rasbian. e.g. something like the  busybox version

**Comment by PierreScerri** [comment] 2020-11-20 17:38
The fact still remains that on my setup, it used to work but then stopped when it updated to 0.2.1

**Comment by dceejay** [comment] 2020-11-20 17:39
do they run it in a container ?

**Comment by PierreScerri** [comment] 2020-11-20 17:41
I have the plain old Hassio type install using the image and a RPi3B.

**Comment by dceejay** [comment] 2020-11-20 17:41
If it is HA - then we need someone who actually runs HA to step up and  debug/fix it for us  by actually editing the code - we can't isolate the problem by guessing.

**Comment by PierreScerri** [comment] 2020-11-20 17:42
In any case I no longer use that ping.

I use node-red-contrib-advanced-ping  which works.

**Comment by dceejay** [comment] 2020-11-20 17:43
that doesn't help fix it does it ?

**Comment by PierreScerri** [comment] 2020-11-20 17:44
No it doesn't.

**Comment by PierreScerri** [comment] 2020-11-20 17:50
These comments were made in July:

https://github.com/node-red/node-red-nodes/issues/662#issuecomment-660477767
https://github.com/node-red/node-red-nodes/issues/662#issuecomment-660479699

**Comment by dceejay** [comment] 2020-11-20 18:01
Ok - lets revert it then - and go from there.

**Comment by dceejay** [comment] 2020-11-20 18:08
Can you try it now with 0.2.2  ?

**Comment by PierreScerri** [comment] 2020-11-20 18:10
Was doing that just before you posted.  Let me see.

**Comment by PierreScerri** [comment] 2020-11-20 18:14
Yep. That Works.

**Comment by dceejay** [comment] 2020-11-20 18:15
Ok - thanks for being so patient...  will close this now and we can all go to the weekend !

**Comment by PierreScerri** [comment] 2020-11-20 18:15
Thank you.

**Closed by dceejay** 2020-11-20 18:15 UTC
Labels: OK to Close ?, invalid
