### ISSUE TITLE
PWM Select frequency and precision

### ISSUE THREAD

**Issue by navivfr** [node-red/node-red-nodes#744] opened 2021-01-26 08:12 UTC
hello,

Thx for this really nice job !

PI4 | Ubuntun 20
All latest install (including python 3 fix)

2 points :

- if I set the msg.payload to 100. In the oscilloscope I dont get a 'flat' output. More like a 99% duty.
- frequency seem to be set a 800Hz. There is a way to change it (ie 2Khz)

REM : on python I can set frequency (I tested 42Khz without any issue), and the Duty precision is crazy (Nice Dirac peak)
From 0 to 1.000.000 (100% duty)

BR

**Comment by navivfr** [comment] 2021-01-26 08:19
oops this message was for giopd... sorry

**Comment by hardillb** [comment] 2021-01-26 08:21
Please make sure to fully read and fill out the template you were shown when you opened this issue.

**Comment by hardillb** [comment] 2021-01-26 08:36
Closed as duplicate of #745

**Closed by hardillb** 2021-01-26 08:36 UTC
