### ISSUE TITLE
node-red-node-wemo no longer finding devices

### ISSUE THREAD

**Issue by kbirger** [node-red/node-red-nodes#690] opened 2020-09-24 11:33 UTC
### Which node are you reporting an issue on?
node-red-node-wemo
### What are the steps to reproduce?
Trying to search for nodes
### What happens?
Not found
### What do you expect to happen?
Them be found - like before
### Please tell us about your environment:

- [ ] Node-RED version: 1.0.3
- [ ] node.js version: 10.16.3
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Linux
- [ ] Browser: N/A. Chrome, Brave, Vivaldi, Firefox, IE, Edge

Basically, I had a flow with some wemo nodes. It used to work, until one day it didn't. Now, it just says searching forever. If I try to update the node and select the device again, the node finds none. My wemo devices still work with the official app, google home app, and other integrations.

![image](https://user-images.githubusercontent.com/165643/94139765-3213bf00-fe38-11ea-8e34-d298396f6979.png)

Also, logs are not helpful, unless I'm looking at the wrong ones. `systemctl status node-red` yields:

> Sep 24 07:31:07 Node-RED[10020]: no device found
Sep 24 07:31:07 Node-RED[10020]: no device found
Sep 24 07:32:05 Node-RED[10020]: no device found
Sep 24 07:32:05 Node-RED[10020]: no device found
Sep 24 07:33:05 Node-RED[10020]: no device found
Sep 24 07:33:05 Node-RED[10020]: no device found
Sep 24 07:34:05 Node-RED[10020]: no device found

**Comment by hardillb** [comment] 2020-09-24 11:40
- Have you let the app upgrade the firmware on the devices recently?
 - What type of device are you using?
 - Have you applied any updates to your linux environment recently that might change the firewall?
 - What version of Linux are you using?

**Comment by kbirger** [comment] 2020-09-24 11:45
Wow thanks for the quick reply @hardillb 

- This has been going on for a while. I was hoping that it would just fix itself (wemo, as you probably know is not super stable). So I don't quite remember whether there was any firmware upgrade available either directly before or after the problem started. As of right now, the devices are on the latest firmware. 

- I am using a Wemo mini smart plug
- No. And to make sure, I have reproduced the problem with ufw off entirely.
- Mint Linux 19

**Comment by hardillb** [comment] 2020-09-24 12:27
OK, I've not updated the firmware on mine in years (probably not since I wrote the node)

Can you find the `node-red-node-wemo` directory, it's probably in `~/.node-red/node_modules` and edit the `lib/wemo.js` file.

If you uncomment lines 132, 242  and  add a similar line after line 226 then restart node-red it should print out each time it finds a device.

This is to check if the search is finding anything. It could be that the device ids have changed at some point.

**Comment by kbirger** [comment] 2020-09-24 14:33
line 243 is hit once per each of my plugs. It sees an IP and reports this: "-urn:schemas-upnp-org:device:Basic:1"

**Comment by hardillb** [comment] 2020-09-24 14:40
Interesting, 243 is for things we don't think are sockets. Looks like a firmware update may have changed how they respond.

Can you add the following line after 243. This will dump the full response from the device so I can try and work out how to parse it.

```
console.log(json);
```

**Comment by hardillb** [comment] 2020-09-24 14:43
Actually make that

```
console.log(JSON.stringify(json, 2));
```

**Comment by kbirger** [comment] 2020-09-24 15:46
Oh, interesting. That IP belongs to my Hue Bridge. 
```json
{
  "root": {
    "$": {
      "xmlns": "urn:schemas-upnp-org:device-1-0"
    },
    "specVersion": [
      {
        "major": [
          "1"
        ],
        "minor": [
          "0"
        ]
      }
    ],
    "URLBase": [
      "http://192.168.1.233:80/"
    ],
    "device": [
      {
        "deviceType": [
          "urn:schemas-upnp-org:device:Basic:1"
        ],
        "friendlyName": [
          "Philips hue (192.168.1.233)"
        ],
        "manufacturer": [
          "Signify"
        ],
        "manufacturerURL": [
          "http://www.philips-hue.com"
        ],
        "modelDescription": [
          "Philips hue Personal Wireless Lighting"
        ],
        "modelName": [
          "Philips hue bridge 2015"
        ],
        "modelNumber": [
          "BSB002"
        ],
        "modelURL": [
          "http://www.philips-hue.com"
        ],
        "serialNumber": [
          "ecb5fa1c9b1a"
        ],
        "UDN": [
          "uuid:2f402f80-da50-11e1-9b23-ecb5fa1c9b1a"
        ],
        "presentationURL": [
          "index.html"
        ],
        "iconList": [
          {
            "icon": [
              {
                "mimetype": [
                  "image/png"
                ],
                "height": [
                  "48"
                ],
                "width": [
                  "48"
                ],
                "depth": [
                  "24"
                ],
                "url": [
                   "hue_logo_0.png"
                 ]
               }
             ]
           }
         ]
       }
     ]
   }
 }
```

This made me realize something though. I think it is a network issue. I set my wemos onto a separate subnet as part of some security efforts. The server does have the ability to reach those devices if I do a ping.

I wonder if ther's a way I can manually set the IPs for a device. At least that would prove  whether it is only a discovery issue.

**Comment by hardillb** [comment] 2020-09-24 16:19
OK, Yes that is definitely the problem. 

The Node-RED instance needs to be on the same subnet as the devices to be able to discover them, ssdp uses broadcasts on the subnet to trigger discovery.

If you want to provide a pull request to add support for hard coded IP addresses then I'm happy to review it and merge, but it's not something I'd be looking to add to this at the moment.

p.s. It also means that your mobile app will be going via the cloud for every command.

**Comment by kbirger** [comment] 2020-09-24 18:05
I'll take a look at that when I have some time. Why do you think my mobile app will be going through the cloud? Discovery still worked fine with this setup because I connected to the wifi of the plug in order to set it up

**Comment by hardillb** [comment] 2020-09-24 18:21
Yes, for the setup you connect directly to the plug, but once set up the mobile app uses the same discovery mechanism as Node-RED, if it can't find the devices locally all the commands will go via the cloud.

**Comment by hardillb** [comment] 2020-09-24 18:21
I'm going to close this issue now as the node is working as intended.

**Closed by hardillb** 2020-09-24 18:21 UTC

**Comment by kbirger** [comment] 2020-09-24 18:32
I didn't know. Thanks for the info. Maybe I'll figure out another way. Thanks for troubleshooting!
